services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_tunnel
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    # Uncomment the following lines if using a configuration file
    # volumes:
    #   - ./config/config.yml:/etc/cloudflared/config.yml
    #   - ./config:/etc/cloudflared
