http:
  # Routers
  routers:
    proxmox:
      entryPoints:
        - "websecure"
      rule: "Host(`proxmox.home.mohand-hamadouche.info`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: proxmox
    pihole:
      entryPoints:
        - "websecure"
      rule: "Host(`pihole.home.mohand-hamadouche.info`)"
      middlewares:
        - default-headers
        - https-redirectscheme
        - pihole-addprefix
      tls: {}
      service: pihole

  # Services
  services:
    proxmox:
      loadBalancer:
        servers:
          - url: "https://pve01.mohand-hamadouche.info"
        passHostHeader: true
        serversTransport: proxmoxTransport
    pihole:
      loadBalancer:
        servers:
          - url: "https://pihole.home.mohand-hamadouche.info"
        passHostHeader: true
        serversTransport: piholeTransport

  # ServersTransports (for insecureSkipVerify)
  serversTransports:
    proxmoxTransport:
      insecureSkipVerify: true
    piholeTransport:
      insecureSkipVerify: true

  # Middlewares
  middlewares:
    pihole-addprefix:
      addPrefix:
        prefix: "/admin
    authentik:
      forwardAuth:
        address: http://authentik-server:9000/outpost.goauthentik.io/auth/traefik
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-entitlements
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000

